### ISSUE TITLE
Hot water automatically turns on when heating is activated

### ISSUE THREAD

**Issue by RyRyMason** [andrew-codechimp/HA-Hive-Local-Thermostat#43]
When I turn the heating on whether using schedules within HA, boosting or manually turning on it triggers the hot water to also come on. 

Using Zigbee2MQTT and the hive is a SLR2d and a hive mini 

If you require any logs please let me know what you want to see. 

Cheers

**Comment by andrew-codechimp** [comment]
Hi, that's very strange

Silly questions
When using the Hive mini to turn on the heating the hot water doesn't come on then?  Could indicate a wiring fault.
What is showing the water is coming on?  The mini, this integration or both?
Have you used any previous method to control the Hive, some automations with MQTT triggers that might still be around?

If you are familiar with sending MQTT commands manually you can try following this to see if it triggers the water as well?  I use MQTT explorer for this
https://www.zigbee2mqtt.io/devices/SLR2.html#set-heating-mode-to-on-heat-endpoint

I've not seen a 2d device and it's not listed on the Z2M supported devices list so unclear if there's any differences from the 2c which I have to test against.
