### ISSUE TITLE
controls not functioning

### ISSUE THREAD

**Issue by nickg90** [andrew-codechimp/HA-Hive-Local-Thermostat#49]
Just installed 1.0.3 and set up with my hive through Z2MQTT, the sensors report correctly however all the controls are dead.
climate shows nothing and if I press boost nothing happens.

**Comment by nickg90** [comment]
..also when trying to update configuration of integration, it gets stuck then crashes home assistant (twice now)

**Comment by nickg90** [comment]
seems the original issue was because my zigbee topic had a space in it. I changed it to _ and it now works nicely :)

**Comment by nickg90** [comment]
would like to be able to set heating boost lower than 30 mins. 5 min boost would be good..

**Comment by andrew-codechimp** [comment]
Glad you got it working, strange about the spaces in topics, I'll see if I can put some handling around that.
The Hive boost has a default of 30 minutes so I have kept this consistent.
5 mins wouldn't do much for a boost but you could always create an automation to start the heat then turn off in 5 mins.
