### ISSUE TITLE
Automation Bug. Error: HiveEntity.get_entity_value() missing 1 required positional argument: 'default'

### ISSUE THREAD

**Issue by dgibbs64** [andrew-codechimp/HA-Hive-Local-Thermostat#50]
Hello, I have recently started getting this bug. I am unsure if it is related to home assistant 2024.11.1 update, but I only noticed the problem today. I am unsure what it means, but I thought it might be some sort of bug that might need addressing. Hope it helps

```
Executed: November 18, 2024 at 8:58:54 AM
Error: HiveEntity.get_entity_value() missing 1 required positional argument: 'default'
Result:
params:
  domain: climate
  service: turn_on
  service_data: {}
  target:
    device_id:
      - 7b4b40ab70503db72eed4997529fa766
running_script: false
```

**Comment by andrew-codechimp** [comment]
Hi, can you update the integration to 1.0.4 released yesterday. I noticed this issue myself elsewhere and hopefully this will fix it.

**Comment by dgibbs64** [comment]
Thanks, just done that. I will keep an eye on it.
