### ISSUE TITLE
Boiler not heating

### ISSUE THREAD

**Issue by harrynrobinson** [andrew-codechimp/HA-Hive-Local-Thermostat#54]
Hi Andrew,

Apologies if this isn't the place for this. Is it possible that I've messed with the Hive Local Thermostat to the point where it no longer works?

I've been using this plug-in for a few months, working well (thank you). This week the boiler continues to fire up but it doesn't heat. I'm not sure where to start but I was playing with the temperature settings in HA this week and did your recent update around the same time so I'm starting here.

If you see this chart: 
<img width="1172" alt="image" src="https://github.com/user-attachments/assets/2a5400ad-142f-4b84-8ff8-b1ded9e4aa38">

Heating was working up to the 27th and then after then the boiler appears on but it's not putting any heat out. It is around that time I was tinkering with the values here (I wanted to drop the frost protect to 10c and default heat to 15c):
<img width="358" alt="image" src="https://github.com/user-attachments/assets/685af042-f2cc-4df7-a8af-7d08bd910d85">

Could you help me troubleshoot it?

Harry

**Comment by andrew-codechimp** [comment]
Hi Harry,

If you can hear the boiler powering up but things aren't getting warm then you need a heating engineer, at a guess I'd say it's maybe the pump that circulates the hot water round (not a heating engineer but studied this a lot when wiring in my own Hive)

The way the Hive works is it is just a simple relay/switch, it connects two wires together to send a signal (call for heat), when the thermostat in the Hive is hot enough it disconnects those two wires.   The integration only tells the Hive to be overall on/off and the temperature, and since the Hive is powering up the boiler it sounds like the Hive is working.

**Comment by harrynrobinson** [comment]
Thank you for the quick response. It's a holiday home so I can't check in it person so the only indicator I have that it is going on is the HASS chart where it shades orange. Seeing as the temperature doesn't rise and my gas usage is zero (from Octo Energy smart meter), it's clear the boiler isn't firing up. Since I messed with the device temperature settings.

Perhaps some other questions to help troubleshoot. Why is the lowest default setting 16oC?

I want to set the heating to come on when the temp falls below 10oC, but only come on to 12oC. With the default setting being 16oC, it keeps jumping to that each time it comes on.

**Comment by harrynrobinson** [comment]
I also get some odd jumping behavior when I try to reduce the set temperature below 15oC. And it doesn't seem possible. Do you know why that might be?

https://github.com/user-attachments/assets/69e7978f-00fd-4763-8d61-ab7b25e65d89

**Comment by andrew-codechimp** [comment]
Thanks for additional information.

So the orange heating in that chart is the Hive giving status updates that it's asking for heat, it's not getting any status from the boiler, but the fact the temperature isn't rising and you are not using gas suggests the boiler isn't heating properly.

The minimum of 15 degrees is to reflect what you can turn the Hive dial down to, the HA dashboard control will allow it to be turned lower, but as soon as you set it you send a command to the Hive and it then reports back what it is doing (min 15) then the UI control resets to what is reflected on the physical device.

The frost protect works the same as the physical control unit, if you set it at 10 it will come on when below 10 and switch off again when above 10, again this is just a command sent to the hive, I'm not doing any controlling logic within the integration.

**Comment by harrynrobinson** [comment]
Yeah, make sense. Hive is just on or off, and it receives no data from the boiler back.

Ok, thank you for looking at this, I'll keep troubleshooting.

**Comment by harrynrobinson** [comment]
A courtesy loop closure here - there was a leaky radiator, the water pressure had dropped to near zero and the boiler cut out.

Nothing to do with this integration, or Hive, as you predicted. Apologies for the false alarm.

**Comment by andrew-codechimp** [comment]
Thanks for the update of the cause, hopefully you didn't have too much of a mess to clear up.
