### ISSUE TITLE
ZHA Support?

### ISSUE THREAD

**Issue by dgibbs64** [andrew-codechimp/HA-Hive-Local-Thermostat#6]
Hello. I was wondering if this works with ZHA? I have managed to get the Hive thermostat and receiver all connected up to ZHA and I stumbled across your repo. It would be great if I could enable the extra functionality you have added but this appears to only support Zigbee2MQTT? Thank you

**Comment by andrew-codechimp** [comment]
Hi, sorry it doesn't. ZHA devices are exposed very differently to MQTT so wouldn't be able to adjust the code. It would be easier for someone to start from scratch than try to build for both.

**Comment by dgibbs64** [comment]
That's a shame. TBH I'm just glad I got it linked up without the hive hub. Thanks for your quick response 👍🏻

**Comment by yurividal** [comment]
> That's a shame. TBH I'm just glad I got it linked up without the hive hub. Thanks for your quick response 👍🏻

@dgibbs64 did you ever get it to work with ZHA? I'm using ZHA and wpuld like to retire my hive hub, but i'd love to still be able to set boost mode, boost duration, and the anti-freeze temperatures.

**Comment by dgibbs64** [comment]
No I didn't. I ultimately moved to Zigbee2MQTT which I found works better for me. I now have a fully working Hive setup without the hub
