### ISSUE TITLE
Trouble working with SLR1c

### ISSUE THREAD

**Issue by largemitch** [andrew-codechimp/HA-Hive-Local-Thermostat#7]
Hey love the idea having issues with it working just comes up with climate unknown.
I have renamed it to match your example to check it’s not that.
Here abit of the mqtt read out just to check its they same as you SLR2c

`{"linkquality":51,"local_temperature":17.7,"occupied_heating_setpoint":15.5,"running_state":"idle","system_mode":"heat","temperature_setpoint_hold":true,"temperature_setpoint_hold_duration":65535}
`

thanks

**Comment by andrew-codechimp** [comment]
Hi, the SLR1x were just a guess so I'm not surprised there are problems.

That json dump really helps, the SLR2x has local_temperature_heat/local_temperature_water etc. I was hoping the SLR1x just didn't expose the water but kept the same names for heat.

I'll be able to fix this fairly easily.

**Comment by largemitch** [comment]
Worked perfect thank you I’ll keep you updated if anything changes with later releases. Thank you

**Comment by andrew-codechimp** [comment]
Thanks for the quick confirmation, hopefully I've covered all the MQTT messages now.
